# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      # run the linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      # run the formatter
      - id: ruff-format
  - repo: https://github.com/dosisod/refurb
    rev: v1.28.0
    hooks:
      - id: refurb
        # additional_dependencies:
        #   - mypy<1.7 # SEE: https://github.com/dosisod/refurb/issues/305
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.0
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v3.1.0
  #   hooks:
  #     - id: prettier
  # - repo: https://github.com/returntocorp/semgrep
  #   rev: v1.50.0
  #   hooks:
  #     - id: semgrep
  #       args: ["--config", "auto", "--error", "--skip-unknown-extensions"]
