language: python
python:
  - "3.8"
  - "3.9"
  # - "3.10"
  # - "nightly"

install:
  - pip install --upgrade pip
  - pip install pip-tools
  - pip-compile --extra dev
  - pip install -r requirements.txt
  - pip install .

script:
  - pytest --cov-report=xml --cov=./euchre/

after_success:
  - codecov

deploy:
  # deploy develop branch to test pypi
  - provider: pypi
    server: https://test.pypi.org/legacy/
    username: __token__
    password: $PYPI_TEST_TOKEN
    skip_cleanup: true
    skip_existing: true
    distributions: sdist bdist_wheel
    on:
      branch: develop
      python: "3.8"

  # deploy release tag to pypi
  - provider: pypi
    username: __token__
    password: $PYPI_TOKEN
    skip_cleanup: true
    skip_existing: true
    distributions: sdist bdist_wheel
    on:
      tags: true
      python: "3.8"

  # deploy release tag docs to github pages
  - provider: pages
    local_dir: docs
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
      tags: true
      python: "3.8"
