language: python
python:
  - "3.7"

install:
  # - pip install --upgrade pip
  # - pip install pip-tools
  - pip-compile
  - pip install -r requirements.txt
  - pip install .

script:
  - pytest

deploy:
  # deploy develop branch to test pypi
  - provider: pypi
    server: https://test.pypi.org/legacy/
    username: __token__
    password: $PYPI_TEST_TOKEN
    skip_cleanup: true
    distributions: sdist bdist_wheel
    on:
      branch: develop
  # deploy tag to pypi
  - provider: pypi
    username: __token__
    password: $PYPI_TOKEN
    skip_cleanup: true
    distributions: sdist bdist_wheel
    on:
      tags: true
  # deploy tag docs to github pages
  - provider: pages
    local_dir: docs
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
      tags: true
